version: "3.8"
services:
  app:
    build: .
    container_name: investbi_next_${ENV:-prod}
    ports:
      - "${PORT:-3000}:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
