name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SERVER }} >> ~/.ssh/known_hosts

      - name: Deploy to Test or Prod
        env:
          BRANCH: ${{ github.ref_name }}
          SERVER: ${{ secrets.SERVER }}
          USER: ${{ secrets.USER }}
        run: |
          if [ "$BRANCH" == "dev" ]; then
            ssh $USER@$SERVER "
              cd /var/www/test/devinbi && \
              git pull origin dev && \
              # Check if container exists and rename it if needed
              docker ps -q --filter name=devinbi_test && docker rename devinbi_test devinbi_test_old || echo 'No existing container to rename' && \
              docker compose up -d --build
            "
          elif [ "$BRANCH" == "main" ]; then
            ssh $USER@$SERVER "
              cd /var/www/prod/devinbi && \
              git pull origin main && \
              # Check if container exists and rename it if needed
              docker ps -q --filter name=devinbi_test && docker rename devinbi_test devinbi_test_old || echo 'No existing container to rename' && \
              docker-compose up -d --build
            "
          fi
