name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SERVER }} >> ~/.ssh/known_hosts

      - name: Deploy to Test or Prod
        env:
          BRANCH: ${{ github.ref_name }}
          SERVER: ${{ secrets.SERVER }}
          USER: ${{ secrets.USER }}
        run: |
          if [ "$BRANCH" == "dev" ]; then
            ssh $USER@$SERVER "
              cd /var/www/test/devinbi && \
              git pull origin dev
              docker build -t devinbi_test:latest . && \
              docker stop devinbi_test || true && \
              docker rm devinbi_test || true && \
              docker run -d -p 3001:3000 --name devinbi_test --restart unless-stopped -e NODE_ENV=production devinbi_test:latest && \
              docker image prune -f && \
              docker system prune -a --volumes -f
            "
          elif [ "$BRANCH" == "main" ]; then
            ssh $USER@$SERVER "
              cd /var/www/prod/devinbi && \
              git pull origin main
              docker build -t devinbi_prod:latest . && \
              docker stop devinbi_prod || true && \
              docker rm devinbi_prod || true && \
              docker run -d -p 3000:3000 --name devinbi_prod --restart unless-stopped -e NODE_ENV=production devinbi_prod:latest && \
              docker image prune -f && \
              docker system prune -a --volumes -f
            "
          fi
