name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SERVER }} >> ~/.ssh/known_hosts

      - name: Deploy to Test or Prod
        env:
          BRANCH: ${{ github.ref_name }}
          SERVER: ${{ secrets.SERVER }}
          USER: ${{ secrets.USER }}
        run: |
          if [ "$BRANCH" == "dev" ]; then
            ssh $USER@$SERVER "
              cd /var/www/test/devinbi && \
              git pull origin dev && \

              # Build the Docker image (you can specify the exact tag)
              docker build -t devinbi_test:latest .

              # Stop and remove the old container
              docker stop devinbi_test
              docker rm devinbi_test

              # Run a new container with the latest image
              docker run -d -p 3001:3000 --name devinbi_test devinbi_test:latest
            "
          elif [ "$BRANCH" == "main" ]; then
            ssh $USER@$SERVER "
              cd /var/www/prod/devinbi && \
              git pull origin main && \
              
              # Build the Docker image (you can specify the exact tag)
              docker build -t devinbi_prod:latest .

              # Stop and remove the old container
              docker stop devinbi_prod
              docker rm devinbi_prod

              # Run a new container with the latest image
              docker run -d -p 3000:3000 --name devinbi_prod devinbi_prod:latest
            "
          fi
